#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}                 # You can use {branch} to, for example

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - production

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

# Skipping commits with particular message or from user
skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/       # Regex for matching commit message
  author: John        # Commit author's username, name, email or regexp maching one of these.
